- name: Deployment on K8 cluster
  hosts: host_machine
  tasks:

    - name: Check Minikube status
      command: minikube status
      register: minikube_status
      changed_when: false
      failed_when: false

    - name: Start Minikube
      become: false
      command: minikube start --cpus 4 --memory 8192
      when: "'Running' not in minikube_status.stdout"

    - name: Installing Addons
      become: false
      command: minikube addons enable ingress
      ignore_errors: true

    - name: Applying K8s Command in Repository
      shell: |
        cd ./k8s/
        kubectl delete -f .
        kubectl apply -f .
      changed_when: false
      failed_when: false